# Generated by Django 4.2 on 2026-03-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoBreadth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('pct_above_50dma', models.FloatField()),
                ('pct_above_100dma', models.FloatField()),
                ('pct_above_200dma', models.FloatField()),
            ],
            options={
                'verbose_name': 'Crypto Breadth Indicator',
                'verbose_name_plural': 'Crypto Breadth Indicators',
                'ordering': ['-date'],
            },
        ),
    ]
