# Generated by Django 4.2 on 2026-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoGlobalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('btc_dominance', models.FloatField(blank=True, null=True)),
                ('eth_dominance', models.FloatField(blank=True, null=True)),
                ('active_cryptocurrencies', models.IntegerField(blank=True, null=True)),
                ('total_market_cap', models.FloatField(blank=True, null=True)),
                ('total_volume_24h', models.FloatField(blank=True, null=True)),
                ('altcoin_market_cap', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crypto Global Quote',
                'verbose_name_plural': 'Crypto Global Quotes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CryptoPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crypto Price',
                'verbose_name_plural': 'Crypto Prices',
                'ordering': ['-date', 'symbol'],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CryptoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(choices=[('alt100', 'Altcoin 100 Index'), ('total', 'Total Market Index')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField()),
                ('daily_return', models.FloatField(blank=True, null=True)),
                ('num_constituents', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crypto Index',
                'verbose_name_plural': 'Crypto Indices',
                'ordering': ['-date'],
                'unique_together': {('index_name', 'date')},
            },
        ),
    ]
