# Generated by Django 4.2 on 2026-03-24 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_models', '0002_cryptoglobalquote_cryptoprice_cryptoindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, help_text='What is this model?')),
                ('methodology', models.TextField(blank=True, help_text='How does it work?')),
                ('how_to_trade', models.TextField(blank=True, help_text='How to use the signals')),
                ('asset_class', models.CharField(choices=[('crypto', 'Crypto'), ('equity', 'Equity'), ('fx', 'FX'), ('macro', 'Macro'), ('commodity', 'Commodity'), ('multi', 'Multi-Asset')], default='crypto', max_length=20)),
                ('frequency', models.CharField(choices=[('tick', 'Tick'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('current_signal', models.CharField(blank=True, choices=[('bullish', '🟢 Bullish'), ('bearish', '🔴 Bearish'), ('neutral', '⚪ Neutral')], max_length=20, null=True)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page_url', models.CharField(blank=True, max_length=200)),
                ('data_model', models.CharField(blank=True, help_text='Django model name for data', max_length=100)),
                ('analysts', models.ManyToManyField(blank=True, related_name='assigned_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quantitative Model',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModelDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('signal', models.CharField(blank=True, choices=[('bullish', '🟢 Bullish'), ('bearish', '🔴 Bearish'), ('neutral', '⚪ Neutral')], max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='crypto_models.quantmodel')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ModelSignalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=20)),
                ('interval_label', models.CharField(help_text='e.g. 1D, 1W, 1M, 3M', max_length=20)),
                ('interval_days', models.IntegerField()),
                ('avg_return_pct', models.FloatField()),
                ('hit_rate_pct', models.FloatField()),
                ('sample_size', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_results', to='crypto_models.quantmodel')),
            ],
            options={
                'verbose_name': 'Signal Result',
                'ordering': ['model', 'signal_type', 'interval_days'],
                'unique_together': {('model', 'signal_type', 'interval_label')},
            },
        ),
        migrations.AddIndex(
            model_name='modeldatapoint',
            index=models.Index(fields=['model', 'timestamp'], name='crypto_mode_model_i_d16ec8_idx'),
        ),
    ]
