# Generated by Django 4.2 on 2026-03-24 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_models', '0003_quantmodel_modeldatapoint_modelsignalresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('instrument', models.CharField(help_text='e.g. BTCUSDT, SPY', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('total_return_pct', models.FloatField(blank=True, null=True)),
                ('sharpe_ratio', models.FloatField(blank=True, null=True)),
                ('max_drawdown_pct', models.FloatField(blank=True, null=True)),
                ('win_rate_pct', models.FloatField(blank=True, null=True)),
                ('total_trades', models.IntegerField(blank=True, null=True)),
                ('avg_trade_duration_days', models.FloatField(blank=True, null=True)),
                ('profit_factor', models.FloatField(blank=True, null=True)),
                ('expectancy', models.FloatField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backtests', to='crypto_models.quantmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquityPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equity_curve', to='crypto_models.backtest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DrawdownPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('drawdown_pct', models.FloatField()),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawdown_curve', to='crypto_models.backtest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BacktestTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('exit_date', models.DateTimeField()),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10)),
                ('return_pct', models.FloatField()),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('duration_days', models.FloatField(blank=True, null=True)),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='crypto_models.backtest')),
            ],
            options={
                'ordering': ['entry_date'],
            },
        ),
        migrations.AddIndex(
            model_name='equitypoint',
            index=models.Index(fields=['backtest', 'timestamp'], name='crypto_mode_backtes_fc7f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='drawdownpoint',
            index=models.Index(fields=['backtest', 'timestamp'], name='crypto_mode_backtes_fb4aee_idx'),
        ),
    ]
