# Generated by Django 4.2 on 2026-03-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_models', '0004_backtest_equitypoint_drawdownpoint_backtesttrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='alpaca', max_length=20)),
            ],
            options={
                'verbose_name': 'Stock Price',
                'ordering': ['-date', 'symbol'],
                'unique_together': {('symbol', 'date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='MacroDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('fred', 'FRED'), ('worldbank', 'World Bank'), ('custom', 'Custom')], db_index=True, max_length=20)),
                ('series_id', models.CharField(db_index=True, help_text='e.g. FRED: DGS10, WB: NY.GDP.MKTP.CD', max_length=100)),
                ('series_name', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(db_index=True)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='US', max_length=10)),
            ],
            options={
                'verbose_name': 'Macro Data Point',
                'ordering': ['-date'],
                'unique_together': {('source', 'series_id', 'date')},
            },
        ),
    ]
