# Generated by Django 4.2 on 2026-03-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_models', '0007_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtest',
            name='avg_losing_trade_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='avg_winning_trade_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='benchmark_return_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='best_trade_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='end_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='heatmap_data',
            field=models.JSONField(blank=True, help_text='Threshold optimization heatmap', null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='heatmap_x_label',
            field=models.CharField(blank=True, default='Long Threshold', max_length=100),
        ),
        migrations.AddField(
            model_name='backtest',
            name='heatmap_y_label',
            field=models.CharField(blank=True, default='Short Threshold', max_length=100),
        ),
        migrations.AddField(
            model_name='backtest',
            name='max_drawdown_duration_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='start_value',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.AddField(
            model_name='backtest',
            name='worst_trade_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
