# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_models', '0008_backtest_avg_losing_trade_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquityBreadth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('pct_above_50dma', models.FloatField()),
                ('pct_above_100dma', models.FloatField()),
                ('pct_above_200dma', models.FloatField()),
                ('pct_outperforming_spx', models.FloatField(blank=True, null=True)),
                ('num_constituents', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Equity Breadth Indicator',
                'verbose_name_plural': 'Equity Breadth Indicators',
                'ordering': ['-date'],
            },
        ),
    ]
