# Generated by Django 4.2 on 2026-03-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_analyst',
            field=models.BooleanField(default=False),
        ),
    ]
