# Generated by Django 4.2 on 2026-03-24 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_postreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='report_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
